version: '3.8'

services:
  whitelistmcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: whitelistmcp:latest
    container_name: whitelistmcp-mcp
    restart: unless-stopped
    environment:
      # Default configuration (can be overridden)
      - AWS_DEFAULT_REGION=us-east-1
      - WHITELIST_MCP_PORT=22
      - WHITELIST_MCP_PROTOCOL=tcp
      - WHITELIST_MCP_RATE_LIMIT=60
    volumes:
      # Mount config file if needed
      - ./mcp_config.json:/app/mcp_config.json:ro
      # Mount logs directory
      - ./logs:/app/logs
    # For MCP server, we typically use stdin/stdout
    stdin_open: true
    tty: true
    # Security settings
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp
    # Resource limits
    mem_limit: 512m
    cpus: '0.5'
    
  # Development service with hot reload
  whitelistmcp-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    image: whitelistmcp:dev
    container_name: whitelistmcp-mcp-dev
    volumes:
      - ./whitelistmcp:/app/whitelistmcp:ro
      - ./tests:/app/tests:ro
      - ./mcp_config.json:/app/mcp_config.json:ro
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - AWS_DEFAULT_REGION=us-east-1
    stdin_open: true
    tty: true
    command: python -m whitelistmcp.main -v